// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD58zd0Ow-3yYEtmTyZFOE3s5L9hI8B-ds',
    appId: '1:793593937921:web:82271b0bdbcd2d8ae38000',
    messagingSenderId: '793593937921',
    projectId: 'amoi-1998',
    authDomain: 'amoi-1998.firebaseapp.com',
    storageBucket: 'amoi-1998.appspot.com',
    measurementId: 'G-6745FFKM0R',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBrCY6ntvW8l1LGYLUyl3ttX6SlKj3lmP4',
    appId: '1:793593937921:android:24411152f44eeebfe38000',
    messagingSenderId: '793593937921',
    projectId: 'amoi-1998',
    storageBucket: 'amoi-1998.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCqwylaeGL-wTUHNZzDDf-7WwR8DfLSTYg',
    appId: '1:793593937921:ios:daaa82ec8a95b890e38000',
    messagingSenderId: '793593937921',
    projectId: 'amoi-1998',
    storageBucket: 'amoi-1998.appspot.com',
    iosClientId: '793593937921-flpiu1vrv3ik35r9hlnlitprbemnpdk6.apps.googleusercontent.com',
    iosBundleId: 'bo.studio.amoi',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCqwylaeGL-wTUHNZzDDf-7WwR8DfLSTYg',
    appId: '1:793593937921:ios:daaa82ec8a95b890e38000',
    messagingSenderId: '793593937921',
    projectId: 'amoi-1998',
    storageBucket: 'amoi-1998.appspot.com',
    iosClientId: '793593937921-flpiu1vrv3ik35r9hlnlitprbemnpdk6.apps.googleusercontent.com',
    iosBundleId: 'bo.studio.amoi',
  );
}
